### ISSUE TITLE
Feature request: Middleware

### ISSUE THREAD

**Issue by EvHaus** [Danilqa/node-file-router#25]
Thanks for the great library. It would be nice if the library allowed a way to provide `middleware` similar to [express middleware](https://expressjs.com/en/guide/using-middleware.html), or [`next-api-middleware`](https://github.com/htunnicliff/next-api-middleware).

This way I could easily specify which routes should be authenticated-vs-public, or create a middleware for catching and handling errors consistently across all routes, or set consitent headers for all responses, etc...

Is this a feature you would consider adding? Or do you recommend using [Custom Adapters](https://danilqa.github.io/node-file-router/docs/custom-adapter/) for this somehow?

**Comment by Danilqa** [comment]
@EvHaus Hi! Thank you very much :)

I've been considering adding them, for sure, but I've waited for the right moment to discuss it with the community first. I am thinking about such an API:
```
api/
├── profile/
│   ├── orders.[get].ts
│   └── middleware.ts - additional nested middleware, contains auth guard, for instance
├── catalog/
│   └── [[...categories]].ts
├── middleware.ts - contains errors handler, tracing, sentry, etc.
├── index.ts      
└── _404.ts
```

The general usage for the middleware file:
```js
// file: api/middleware.js

export default function middleware(req, res, next) {
   // Setup code
   // ...

   await next(); // <-- The router's code or next middleware (on nested levels)
	
   // ...
   // Teardown code
}

// Optional config to include or exclude some routes
export const config = {
   matcher: '/((?!(ping|health-check).*)',
}
```

Also, we can export a pipeline with middlewares:
```js
// file: api/middleware.js

export default [
    useLogger,
    useSentry,
    useAudit
];
```

And now, each route has the ability to use middlewares as well:
```js
// file: api/users/index.[post].js

export default [
    useSchemaValidation(PersonSchema),
    createUser,
];

function createUser(req, res) {
   // ...
}
```


Does it meet your needs? How the comfortable API is?

**Comment by EvHaus** [comment]
Yeah, that proposal looks pretty good. Just a few ideas to consider:

1. Since there's already a lot of flexibility/control over where the middleware is used, I'm not sure the `export const config = {matcher}` is needed. I think that might potentially add too much complexity to the API. If you need fine grained control over which file has which middleware, your proposal of exporting an array right from the route file looks more elegant to me.
2. I'm using Bun which only has a `Request` and not a `Response` passed to the routes, so the middleware will need to be flexible enough to support this case. ie. Both `middleware(req, res, next)` and `middleware(req, next)` will need to be supported.
3. It's important for me that the middleware supports returning/bailing early. For example, let's say you want an authentication guard middleware where if the middleware detects that the user is not authenticated it doesn't even call your route code. So performing a `return Response({status: 503})` from insde a middleware should be possible and that should stop all downstream middleware and route handlers from being executed. In other words, middleware can either `return` a response or call `next()` to continue.

**Comment by Danilqa** [comment]
@EvHaus Great, thanks a lot! I'll implement this feature during this week and let you know when it's done.

**Comment by Danilqa** [comment]
@EvHaus Hello! I have implemented the middleware feature and released version `0.5.0`. The documentation can be found here: https://danilqa.github.io/node-file-router/docs/middlewares

Thank you very much for your proposal and for participating in the discussions. I would be happy to hear your feedback and make improvements, if necessary.

**Comment by EvHaus** [comment]
Awesome. I plan to work on integrating this next week. Will provide feedback then!

**Comment by EvHaus** [comment]
Nice work @Danilqa! The implementation is working well for me so far and the docs are great. I only have 1 very minor suggestion:

As a Bun user, I immediately ran into `next is not a function` failures because the documented middleware examples don't work. I had to change `(req, res, next)` to `(req, next)`. It would be nice to include info about middleware usage on the "Usage with Bun" page. Would be helpful to also mention that you'll want the `Request` type if using Typescript. So the full example is:

```ts
import type { NextFunction } from 'node-file-router';

export default function useMyMiddleware(req: Request, next: NextFunction) {
  // Code before
  // ...

  await next(); // <-- The router's code or next middleware (on nested levels)

  // ...
  // Code after
}
```

**Comment by Danilqa** [comment]
@EvHaus very glad to hear that, thank you very much! I will definitely add information about Bun.
