### ISSUE TITLE
`routeParams` is lost when exporting middleware in "Usage in File Routes"

### ISSUE THREAD

**Issue by EvHaus** [Danilqa/node-file-router#34]
I'm seeing a bug when using ["Usage in File Routes"](https://danilqa.github.io/node-file-router/docs/middlewares#usage-in-file-routes). The endpoint method will no longer receive a `routeParams` argument if your default export is an array. I'm guessing `node-file-router` assumes every item in the array is a middleware, whereas I think the last one should be assumed to be a route handler.

I'm using Bun.

The minimal repro looks something like this:

```ts
const createUser = (req, routeParams) => {
  // BUG: I'm expecting this to be `routeParams` but it's actually the `next` method.
  console.log(routeParams)
}

export default [createUser];
```

Changing `export default [createUser];` to `export default createUser;` makes the `routeParams` return correctly again.

The behaviour is the same with `export default [someMiddleware, createUser];`

**Comment by Danilqa** [comment]
@EvHaus Hi!

The fix has been uploaded under version 0.5.2. Now, you are also able to access route parameters inside middlewares, which are used within the route handler.

For instance, the following code will now work correctly:
```ts
async function useMyMiddleware(req: Request, next: NextFunction, routeParams: Record<string, string>) {
  // routeParams now have values here
  await next();
}

async function createOrUpdateUser(req: Request, routeParams: RouteParams) {
  // As well as here
}

export default [
  useMyMiddleware,
  createOrUpdateUser,
];

```

And, for sure, if you just export an array with single function of route handler:
```ts
async function createOrUpdateUser(req: Request, routeParams: RouteParams) {
  // routeParams have values now
}

export default [
  createOrUpdateUser,
];

```

**Comment by EvHaus** [comment]
Confirmed. Works! Thank you for the continued support and fast fixes.

**Comment by Danilqa** [comment]
@EvHaus Thank you for your interest and contribution! Look forward to your next proposals and issues
